### ISSUE TITLE
User Story: Secure Secret Keys

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#10]
As a **Developer**, I want to **keep the secret keys secure**, so that **they are not exposed in the code repository**.

## Tasks

- [x]  Create .env file for secret keys
- [ ]  Install django-environ
- [x]  Add .env to .gitignore

## Epic: #1
