### ISSUE TITLE
User Story: Deploy Site to Heroku

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#11]
As a **Developer**, I want to **deploy the site to Heroku early**, so that **I can start testing in a production-like environment**.

## Tasks

 - [x] Create Heroku app
 - [x] Add Procfile for gunicorn
 - [x] Set up database config for Heroku
 - [x] Deploy app and test

## Epic: #1
