### ISSUE TITLE
User Story: Product Browsing

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#12]
As a **Customer**, I want to **browse products easily**, so that **I can find items to buy**.

## Tasks

 - [x] Create a product model
 - [x] Build product listing page
 - [x] Add search and filter options

## Epic: #2
