### ISSUE TITLE
User Story: Shopping Cart Feature

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#13]
As a **Customer**, I want to **add products to a shopping cart**, so that **I can review and purchase them**.

## Tasks

 - [ ] Create shopping cart model
 - [ ] Implement add-to-cart button
 - [ ] Display cart items on a cart page

## Epic: #2
