### ISSUE TITLE
User Story: Complete Purchase

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#15]
As a **Customer**, I want to **checkout and complete the purchase**, so that **I can pay for the items in my cart**.

## Tasks

 - [x] Integrate Stripe for payments
 - [x] Create a checkout page
 - [x] Send order confirmation email

## Epic: #3
