### ISSUE TITLE
User Story: User Registration and Login

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#17]
As a User, I want to register and log in to the site, so that I can save my shopping cart and make purchases.

## Tasks

 - [x] Set up user registration using django-allauth
 - [x] Create a profile page for users
 - [x] Implement forgot password functionality

## Epic: #4
