### ISSUE TITLE
User Story: Newsletter Signup

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#20]
As a **Customer**, I want to **sign up for a newsletter**, so that **I can get updates about new products**.

## Tasks

 - [x] Implement newsletter signup form
 - [x] Connect the form to MailChimp
 - [x] Send confirmation email

## Epic: #5
