### ISSUE TITLE
User Story: Comprehensive Unit and Integration Testing

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#25]
As a **Developer**, I want to **write and run tests for my application**, so that **I can ensure it is bug-free and functional**.

## Tasks

 - [x] Write unit tests for models
 - [x] Write integration tests for all user flows
 - [x] Test payment processing functionality

## Epic: #8
