### ISSUE TITLE
User Story: Final Deployment on Heroku

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#26]
As a Developer, I want to finalize deployment, so that the site is live and functional for users.

## Tasks

 - [ ] Set DEBUG to False in production
 - [ ] Test live site on Heroku
 - [ ] Verify all features work post-deployment

## Epic: #8
