### ISSUE TITLE
User Story: Set Up Django for Development

### ISSUE THREAD

**Issue by Salewitcher** [Salewitcher/star_wardrobe#9]
As a **Developer**, I want to **set up Django and install the supporting libraries**, so that **I am ready to start development**.

## Tasks

- [x]  Install Django
- [x]  Install gunicorn
- [x]  Install allauth
- [x]  Create requirements.txt
- [x]  Create Django project – star_wardrobe
- [x]  Create the first app and add it to settings.py

## Epic: #1
